#!/usr/bin/env ruby
require_relative '../app'
mongo_path = File.expand_path(File.join(WorkflowServer::Config.root, "config", "mongoid.yml"))
Mongoid.load!(mongo_path, WorkflowServer::Config.environment)

args = ARGV.last

eval(args)